plugins {
    id 'com.android.application'
}

android {
    namespace 'com.elta.entregas_doc'
    compileSdk 34

    defaultConfig {
        applicationId "com.elta.entregas_doc"
        minSdk 24
        targetSdk 34
        versionCode 46
        versionName "4.6"
    }
}


dependencies {
    implementation "androidx.core:core:1.13.1"
}
